Default image tag to .Chart.AppVersion
kubernetes/cloud-provider-openstack pull request #1219
Opened 2020-09-16 12:27 UTC by brtknr

(cherry picked from commit deff98638e9a178cf958cabd4a9daaa7c3aac680)

**What this PR does / why we need it**:

**Which issue this PR fixes(if applicable)**:
fixes #

**Special notes for reviewers**:

**Release note**:

```release-note
NONE
```

2020-09-17 04:24 UTC, ramineni requested changes

2020-09-17 04:24 UTC, ramineni commented on charts/manila-csi-plugin/Chart.yaml
>  appVersion: latest
@brtknr appVersion need to be updated here , v1.19.0

2020-09-17 04:24 UTC, ramineni commented
/ok-to-test

2020-09-18 06:20 UTC, ramineni commented
@brtknr Is it required to backport this, this is not a bug but only an improvement . We only backport critical/required fixes as need basis

2020-09-18 06:21 UTC, ramineni commented
/hold

2020-09-23 12:57 UTC, ramineni commented
@brtknr Is this required for 1.19 , as I mentioned we only backport bug fixes .

2020-09-23 13:26 UTC, brtknr commented
Hi @ramineni I agree it is an improvement but since there hasn't been a working chart release yet, it would be safe to incorporate this into the first chart release from v1.19.0 branch.

2020-09-26 01:21 UTC, lingxiankong commented
I think it's fine to have this for release-1.19, hopefully we could have some official, stable Charts for this release.

/lgtm

2020-09-28 04:22 UTC, ramineni commented
> Hi @ramineni I agree it is an improvement but since there hasn't been a working chart release yet, it would be safe to incorporate this into the first chart release from v1.19.0 branch. I have seen other changes backported too which are not strictly bug fixes, e.g. the snapshotter image version bump.

@brtknr ok, sounds reasonable. by the way , snapshotter version bump is a required fix , otherwise snapshot feature doesnt work due to incompatible of sidecar versions.

2020-09-28 04:23 UTC, ramineni commented on charts/manila-csi-plugin/Chart.yaml
>  appVersion: latest
this is not addressed?

2020-09-28 04:32 UTC, ramineni commented
@brtknr As we want stable release of charts as @lingxiankong mentioned, as an exception, we could incorporate these changes .
please address comment , this should be good to go

2020-09-28 08:35 UTC, ramineni commented
/lgtm

2020-09-28 08:36 UTC, ramineni commented
/hold cancel

2020-09-28 09:27 UTC, brtknr commented
This needs /approved label to merge. Assuming that @lingxiankong disabled branch protection on gh-pages branch, this should correctly create a new release and publish to charts.yaml.

2020-09-28 10:11 UTC, ramineni commented
As we already have lgtm from @lingxiankong , approving this.
/approve

2020-09-28 10:12 UTC, merged