[cinder-csi-plugin] Improve docs [Part2]
kubernetes/cloud-provider-openstack pull request #1254
Opened 2020-10-01 09:35 UTC by ramineni

This splits the docs to diff files for better readability

**What this PR does / why we need it**:

**Which issue this PR fixes(if applicable)**:
fixes #

**Special notes for reviewers**:

**Release note**:

```release-note
NONE
```

2020-10-07 05:21 UTC, ramineni commented
/assign @lingxiankong

2020-10-11 01:18 UTC, lingxiankong requested changes

2020-10-11 01:18 UTC, lingxiankong commented on docs/cinder-csi-plugin/csc-tool.md
> +$
Please remove this line.

2020-10-12 04:17 UTC, ramineni commented on docs/cinder-csi-plugin/csc-tool.md
> +$
done

2020-10-12 05:41 UTC, lingxiankong commented
/lgtm

2020-10-12 06:57 UTC, jichenjc commented
/approve

2020-10-12 07:12 UTC, merged