[manila-csi-plugin] Fix whitespaces and invalid dot
kubernetes/cloud-provider-openstack pull request #1285
Opened 2020-10-22 15:46 UTC by isantospardo

**What this PR does / why we need it**:

Chart removes whitespace too aggressively in 
https://github.com/kubernetes/cloud-provider-openstack/blob/master/charts/manila-csi-plugin/templates/controllerplugin-statefulset.yaml#L138-L149

and 

https://github.com/kubernetes/cloud-provider-openstack/blob/master/charts/manila-csi-plugin/templates/nodeplugin-daemonset.yaml#L128-L139

I saw this when trying to set `.Values.controllerplugin.nodeSelector` or `.Values.nodeplugin.nodeSelector`

**Which issue this PR fixes(if applicable)**:
fixes #1284

**Special notes for reviewers**:
Impossible to set `.Values.controllerplugin.nodeSelector` or `.Values.nodeplugin.nodeSelector`

**Release note**:
1. Fix possibility to set `.Values.controllerplugin.nodeSelector` or `.Values.nodeplugin.nodeSelector`

2020-10-22 16:21 UTC, isantospardo commented
/retest

2020-10-22 17:01 UTC, gouthampacha commented
/ok-to-test

2020-10-22 17:02 UTC, gouthampacha commented
/assign @gman0 @tombarron @gouthampacha

2020-10-23 01:50 UTC, jichenjc commented
I saw the test passed for chart but not sure it's functional tested or not...

/lgtm

2020-10-23 08:07 UTC, isantospardo commented
@jichenjc before this patch, I was seeing the following error
```
rpc error: code = Unknown desc = Failed to unmarshal manifest: error converting YAML to JSON: yaml: line 115: mapping values are not allowed in this context
```
I have tried with this patch, and the error is gone and I can set now nodeSelector

2020-10-23 08:13 UTC, jichenjc commented
@isantospardo thanks :) appreciate ~

2020-10-25 10:09 UTC, gman0 requested changes
@isantospardo Thanks for the patch! I can confirm the whitespaces were removed too aggressively. One suggestion though to keep the current style of manifests generated:

```yaml
    {{- if .Values.controllerplugin.affinity }}
      affinity: {{ toYaml .Values.controllerplugin.affinity | nindent 8 }}
    {{- end }}
    {{- if .Values.controllerplugin.nodeSelector }}
      nodeSelector: {{ toYaml .Values.controllerplugin.nodeSelector | nindent 8 }}
    {{- end }}
    {{- if .Values.controllerplugin.tolerations }}
      tolerations: {{ toYaml .Values.controllerplugin.tolerations | nindent 8 }}
    {{- end }}
```

* template statements on new lines start with `{{-` and end with `}}`
* keep the indentation
* inline the `toYaml` pipeline and use `nindent` (does the same thing as `indent`, but prepends a `\n` to the output)

IMHO this is a bit more readable.

Similarly for the node plugin. Would that work for you?

2020-10-26 09:25 UTC, isantospardo commented
@gman0 Thanks for the comments, I just tested and pushed the changes with your suggestions

2020-10-26 11:48 UTC, gman0 approved these changes
@isantospardo Thank you!

/lgtm
/approve

2020-10-26 11:48 UTC, gman0 commented
/assign @ramineni 
/assign @jichenjc 

Can you guys please help us get this merged?

2020-10-26 13:22 UTC, ramineni commented
/lgtm
/approve

2020-10-26 13:23 UTC, merged