[cinder-csi-plugin] chart: better optional cloud-config secret handling
kubernetes/cloud-provider-openstack pull request #1353
Opened 2020-12-18 20:34 UTC by remche

This PR offers better secret handling for `cloud-config` : 

* use an existing secret : 
```yaml
secret:
  use: true
  name: cinder-csi-cloud-config
```

* create a new secret for `cloud-config` :
```yaml
secret:
  use: true
  name: cinder-csi-cloud-config
  data:
    cloud-config: |-
      ...
```

2020-12-21 02:53 UTC, jichenjc commented
/ok-to-test

2020-12-21 02:55 UTC, jichenjc commented
/release-note-none

2020-12-27 05:16 UTC, lingxiankong requested changes

2020-12-27 05:16 UTC, lingxiankong commented on charts/cinder-csi-plugin/values.yaml
> +  use: false
Can we use `enabled` instead of `use`?

2020-12-28 13:14 UTC, remche commented on charts/cinder-csi-plugin/values.yaml
> +  use: false
Totally agree that's better. Fixed !

2020-12-28 19:55 UTC, lingxiankong commented
Haven't tested, but changes look good to me.

/lgtm

2020-12-29 05:17 UTC, ramineni commented on charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
> +        {{- if .Values.secret.use }}
it should be enabled?

2020-12-29 05:17 UTC, ramineni commented on charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml
> +        {{- if .Values.secret.use }}
enabled?

2020-12-29 09:05 UTC, remche commented on charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml
> +        {{- if .Values.secret.use }}
Oops, bad `git add`, fixed.

2021-01-04 02:21 UTC, jichenjc commented
/approve

thanks for the change

2021-01-05 02:31 UTC, lingxiankong commented
/lgtm

2021-01-05 02:37 UTC, merged