[magnum-auto-healer] Fix k8s master node repair if it's volume-based
kubernetes/cloud-provider-openstack pull request #1447
Opened 2021-03-17 21:07 UTC by openstacker

**What this PR does / why we need it**:
Fix k8s master node auto repair if the node is volume-based.

**Which issue this PR fixes(if applicable)**:
fixes #1446 

**Special notes for reviewers**:

**Release note**:
 [magnum-auto-healer] Fix k8s master node repair when the node is volume-based

2021-03-18 03:37 UTC, jichenjc commented
@openstacker maybe you want to update your release note :)

2021-03-18 06:08 UTC, lingxiankong requested changes

2021-03-18 21:21 UTC, openstacker commented on pkg/autohealing/cloudprovider/openstack/provider.go
> +// 	       - Heat stack ID and resource ID.
Resize can handle the volume-based node.

2021-03-18 21:21 UTC, openstacker commented on pkg/autohealing/cloudprovider/openstack/provider.go
> +			// Mark VM as unhealthy
Yep, nice catch.

2021-03-18 21:25 UTC, openstacker commented on pkg/autohealing/cloudprovider/openstack/provider.go
> +				log.Infof("comparing server ID %s with known broken ID %s", serverID, id)
Will do.

2021-03-18 21:28 UTC, openstacker commented on pkg/autohealing/cloudprovider/openstack/provider.go
> +				err = stackresources.MarkUnhealthy(provider.Heat, allMapping[serverID].StackName, allMapping[serverID].StackID, rootVolumeID, opts).ExtractErr()
I will add a IF check

2021-03-18 21:29 UTC, openstacker commented on pkg/autohealing/cloudprovider/openstack/provider.go
> +					log.Warningf("failed to reboot node %s, error: %v", serverID, err)
Nice catch. Will do.

2021-03-18 21:30 UTC, openstacker commented on pkg/autohealing/cloudprovider/openstack/provider.go
> +					log.Warningf("failed to reboot node %s, error: %v", serverID, err)
Reboot and resize are separated actions for the repairing. When there are more than one node failed, they're repaired separately.

2021-03-18 21:32 UTC, openstacker commented on pkg/autohealing/cloudprovider/openstack/provider.go
> +			log.Infof("volume %s is bootable %t", attachment.VolumeID, bootable)
Good point.

2021-03-18 21:34 UTC, openstacker commented on pkg/autohealing/cloudprovider/openstack/provider.go
> +					return false, fmt.Errorf("failed to detach volume %s from instance %s", attachment.VolumeID, serverID)
will do.

2021-03-18 21:34 UTC, openstacker commented on pkg/autohealing/cloudprovider/openstack/provider.go
> +func (provider OpenStackCloudProvider) waitForServerDetachVolumes(serverID string, timeout time.Duration) (string, error) {
Will do.

2021-04-07 01:25 UTC, lingxiankong commented
/lgtm

2021-04-07 01:37 UTC, jichenjc commented
/approve

2021-04-07 09:34 UTC, lingxiankong commented
/approve

2021-04-07 09:39 UTC, merged