[occm] OpenStack Cloud Controller Manager Helm Chart
kubernetes/cloud-provider-openstack pull request #1458
Opened 2021-03-28 00:07 UTC by eumel8

**What this PR does / why we need it**:

Adding Helm Chart for occm deployment

**Which issue this PR fixes(if applicable)**:
none

**Special notes for reviewers**:

none

**Release note**:
```release-note
OpenStack Cloud Controller Manager Helm Chart
```

2021-04-01 08:28 UTC, morremeyer requested changes
Looks good to me for the most part, I PRd some changes (as @eumel8 and I discussed on Slack) to @eumel8's fork directly.

For the part here, there’s only the one change I’d make to the default tolerations.

2021-04-01 08:28 UTC, morremeyer commented on charts/openstack-cloud-controller-manager/values.yaml
> +#     effect: NoExecute
I’d make the commented tolerations the default as I think this is the most common setup and will facilitate configuration for the users.

2021-04-07 02:03 UTC, lingxiankong requested changes
The helm chart is in good shape, besides the comment I've left, can we add more comments for the options in the `values.yaml`? e.g. the default value, what if it's set to true, etc.?

2021-04-07 18:01 UTC, eumel8 commented on charts/openstack-cloud-controller-manager/values.yaml
> +loadbalancerService: {}
I know, this have disadvantages and dependencies, on the other hand it`s a main functionality of occm. Would you suggest an extra Chart only with the service loadbalancer?

2021-04-07 18:06 UTC, morremeyer commented on charts/openstack-cloud-controller-manager/values.yaml
> +loadbalancerService: {}
I agree with @lingxiankong here. The occm should chart should only deploy the occm itself.

services of type LoadBalancers etc. should be created by the applications that need it in their respective charts.

2021-04-08 01:15 UTC, jichenjc commented
/ok-to-test

2021-04-08 08:42 UTC, eumel8 commented on charts/openstack-cloud-controller-manager/values.yaml
> +loadbalancerService: {}
ok,  moved to https://github.com/kubernetes/cloud-provider-openstack/pull/1466

2021-04-15 09:32 UTC, lingxiankong commented
/lgtm

Good to have. Thanks!

2021-04-15 09:45 UTC, jichenjc commented
/approve

thanks

2021-04-15 09:51 UTC, merged