WIP[cinder-csi-plugin] :Add volume condition for controller
kubernetes/cloud-provider-openstack pull request #1585
Opened 2021-07-06 02:57 UTC by jichenjc

**What this PR does / why we need it**:

**Which issue this PR fixes(if applicable)**:
fixes #

**Special notes for reviewers**:

**Release note**:

```release-note
NONE
```

2021-07-06 11:32 UTC, jichenjc commented
/test cloud-provider-openstack-e2e-test-csi-cinder

2021-07-08 05:33 UTC, jichenjc commented
/test cloud-provider-openstack-e2e-test-csi-cinder

2021-07-12 01:28 UTC, jichenjc commented
@lingxiankong @ramineni can you help take a look? The error is not related

2021-07-13 22:11 UTC, lingxiankong requested changes

2021-07-13 22:11 UTC, lingxiankong commented on pkg/csi/cinder/openstack/openstack_volumes.go
> +			return false
I think you mean `return true` here.

2021-07-13 22:11 UTC, lingxiankong commented on pkg/csi/cinder/nodeserver_test.go
> +			Message:  "available",
"available" means abnormal?

2021-07-13 22:11 UTC, lingxiankong commented on pkg/csi/cinder/nodeserver_test.go
> +			Message:  "available",
"available" means abnormal?

2021-07-19 00:41 UTC, jichenjc commented on pkg/csi/cinder/nodeserver_test.go
> +			Message:  "available",
yes, I need update this logic

2021-07-19 00:41 UTC, jichenjc commented on pkg/csi/cinder/nodeserver_test.go
> +			Message:  "available",
ditto

2021-07-20 00:56 UTC, jichenjc commented
/retest

2021-07-20 09:15 UTC, jichenjc commented
/test cloud-provider-openstack-test-csi-cinder

2021-07-21 03:06 UTC, jichenjc commented
/test cloud-provider-openstack-test-csi-cinder

2021-07-26 01:33 UTC, jichenjc commented
/retest

2021-11-02 08:28 UTC, jichenjc commented
@ramineni @lingxiankong can you help review this? 
I Think we can overwrite old openlab CI ? thanks

2021-11-09 04:15 UTC, lingxiankong commented
/override openlab/cloud-provider-openstack-multinode-csi-migration-test
/override openstack-cloud-keystone-authentication-authorization-test

@jichenjc May I know what is the current status of the job openstack-cloud-keystone-authentication-authorization-test? It's here but I see it's never passed.

2021-11-09 04:15 UTC, lingxiankong commented
/lgtm

2021-11-16 10:42 UTC, ramineni commented
@jichenjc Thanks for the PR. Trying to understand better, is this volume conditions are used only if external health monitor is enabled is supported/enabled? not used otherwise? because, I see that external health monitor is a separate sidecar and alpha feature only, so if we dont have plans to add support now , I dont think we should add this

2021-11-16 12:26 UTC, jichenjc commented
@ramineni I thought we should catch up with CSI spec and adopt new features time to time?
or if it's alpha, maybe we can put it as optional feature of CPO? let me know your thoughts :)

2021-11-17 05:03 UTC, ramineni commented
> @ramineni I thought we should catch up with CSI spec and adopt new features time to time? 

@jichenjc +1 , yes I agree.

> or if it's alpha, maybe we can put it as optional feature of CPO? let me know your thoughts :)

Actually 3 things crossed my mind - 
1. I see external health monitor is a big feature and needs proper testing /configuration before adding it here. 
2. As VOLUME_CONDITION is only part of the feature, may be its better to add it as a whole feature with tests enabled.
3. And as its only alpha , Im wondering is it worth the effort , may be we should wait until beta . 

wdyt?

2022-02-23 00:57 UTC, jichenjc commented
/remove-lifecycle stale

2023-05-11 09:30 UTC, closed without merging