Tls exclude ports
kubernetes/cloud-provider-openstack pull request #1639
Opened 2021-09-03 13:15 UTC by reneluria

[oocm] Add annotation to exclude ports from TERMINATED_HTTPS: tls-ports-exclude

**What this PR does / why we need it**:

It adds support for the annotation `loadbalancer.openstack.org/tls-ports-exclude`.
When using `loadbalancer.openstack.org/default-tls-container-ref`, all listeners are creating using TERMINATED_HTTPS

For a multi-port service, having for example, ports 80 and 443, we want some ports to be excluded and use proto HTTP instead, to have plain http on some ports and https on the others

Example:

apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
  name: myapp
  annotations:
    loadbalancer.openstack.org/x-forwarded-for: "true"
    loadbalancer.openstack.org/default-tls-container-ref: "https://api.pub1.infomaniak.cloud/keymanager/v1/containers/e53fd5d0-c3d0-4707-8c20-bbf11796e1b5"
    loadbalancer.openstack.org/tls-ports-exclude: "80"
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: myapp
  type: LoadBalancer
status:
  loadBalancer: {}

**Which issue this PR fixes(if applicable)**:
-none-

**Special notes for reviewers**:

Create the above service with this image, listing listeners for this load balancer via the openstack api, you should get:

+--------------------------------------+--------------------------------------+------+----------------------------------+------------------+---------------+----------------+
| id                                   | default_pool_id                      | name | project_id                       | protocol         | protocol_port | admin_state_up |
+--------------------------------------+--------------------------------------+------+----------------------------------+------------------+---------------+----------------+
| 7f8295ee-ae54-4025-8c12-1ce0695f45b8 | 9ff787d0-87fe-4c2a-ba74-6a819fdf006c |      | 4c08a353d2414273aa43ee0bf6ec2683 | HTTP             |            80 | True           |
| b1e17721-83c8-44d3-ae5a-63b4bd7fcefe | fbeedf15-36d0-45b9-a181-be47d66430cf |      | 4c08a353d2414273aa43ee0bf6ec2683 | TERMINATED_HTTPS |           443 | True           |
+--------------------------------------+--------------------------------------+------+----------------------------------+------------------+---------------+----------------+

**Release note**:
```release-note
NONE
```

2021-09-05 23:56 UTC, jichenjc commented
/ok-to-test

2021-09-10 11:55 UTC, lingxiankong commented
Rather than `loadbalancer.openstack.org/tls-ports-exclude: "80"`, I'd prefer using something like `loadbalancer.openstack.org/service-ssl-ports: "443,8443"` to be more straightforward. Thoughts?

2021-09-10 15:31 UTC, reneluria commented
> Rather than `loadbalancer.openstack.org/tls-ports-exclude: "80"`, I'd prefer using something like `loadbalancer.openstack.org/service-ssl-ports: "443,8443"` to be more straightforward. Thoughts?

yes, why not, here is the new version

2021-09-28 02:02 UTC, lingxiankong requested changes
Does this new annotation support service update?

2021-10-04 13:36 UTC, reneluria commented on pkg/openstack/loadbalancer.go
> +			klog.V(2).Infof("No tlsContainer for excluded port %v", port.Port)
that print statement is not needed, just removed it

2021-10-04 13:39 UTC, reneluria commented on pkg/openstack/loadbalancer.go
> +				return noPorts
good point, fixed

2021-10-04 13:39 UTC, reneluria commented on pkg/openstack/loadbalancer.go
> +func GetTlsServicePorts(service *corev1.Service) ([]int32) {
good point, removed

2021-10-04 13:39 UTC, reneluria commented on pkg/openstack/loadbalancer.go
> +func tlsIsPortIncluded(includedPorts []int32, port int32) bool {
here you go

2022-05-08 08:33 UTC, closed without merging