[cinder-csi-plugin] Updated CLOUD_CONFIG in Helm Chart
kubernetes/cloud-provider-openstack pull request #1715
Opened 2021-12-08 17:02 UTC by powellchristoph

**What this PR does / why we need it**: 

Currently the openstack-ccm helm chart [hardcodes its key name](https://github.com/kubernetes/cloud-provider-openstack/blob/master/charts/openstack-cloud-controller-manager/templates/secret.yaml#L8) when creating its secret as `cloud.conf`. Due to the different secret keys, you must create two separate secrets if running both the CCM and CSI plugin. This change would allow the `cinder-csi-plugin` reuse the existing secret created by the CCM.

```release-note
* Changed CLOUD_CONFIG env var in Helm Chart.
```

2021-12-08 17:07 UTC, powellchristoph commented
Completed CLA Authorization.

2021-12-13 07:55 UTC, jichenjc commented
/ok-to-test

2021-12-13 08:50 UTC, jichenjc commented
I don't remember clearly whether cloud.conf is same in CSI and OCCM
if they do, yes, we need think about make them identical

2021-12-13 15:12 UTC, powellchristoph commented
Just a quick look at the source, it appears that each plugin references their own section in the config file so they should be fine.

2021-12-14 01:07 UTC, jichenjc commented
could you please help to fix the CLA and other issues?

I think it's ok and reasonable to make the secret reusable if we can

2021-12-15 04:09 UTC, lingxiankong requested changes
and please fix the CLA issue.

2021-12-15 04:09 UTC, lingxiankong commented on charts/cinder-csi-plugin/Chart.yaml
> +version: 2.0.1
Version bump will be done during the release, so please keep the version here.

2022-01-19 13:18 UTC, ramineni commented
@powellchristoph I think the issue 2 commits are done with diff usernames. fixing should solve the cla issue

2022-01-19 15:46 UTC, closed without merging

2022-01-19 15:46 UTC, powellchristoph commented
I borked this all up. I'll submit a new one thats proper.