[occm] Replace call to Nova os-interfaces with direct Neutron call
kubernetes/cloud-provider-openstack pull request #2250
Opened 2023-05-19 12:45 UTC by mdbooth

**What this PR does / why we need it**:
os-interfaces is a proxy API for neutron's ports list. This has 2 significant disadvantages to us:
* It adds the overhead of an extra API call every time it is used
* It doesn't contain all the information returned by Neutron

This is a non-functional change, although is does reduce the load on nova-api without reducing functionality.

The primary motivation for this is to enable additional filtering using information from ports, e.g. filtering by port tag or the addition of subports as in #2228.

**Release note**:

```release-note
NONE
```

2023-05-19 12:45 UTC, mdbooth commented
cc @stephenfin @dulek

2023-05-19 13:07 UTC, mdbooth commented
/cc @stephenfin @dulek

2023-05-19 15:50 UTC, stephenfin commented
To the best of my knowledge, the only thing exposed by the nova `/server/{server}/os-interface` API that is not exposed by the `/ports?device_id={server}` API is the device tags. If you don't need those, this should be a no-op.

2023-05-22 01:58 UTC, jichenjc commented
/lgtm

2023-05-23 16:45 UTC, dulek requested changes

2023-05-23 16:45 UTC, dulek commented on pkg/openstack/instances.go
> +		klog.Errorf("unable to access compute v2 API : %v", err)
That's network v2 API here.

2023-05-23 16:45 UTC, dulek commented on pkg/openstack/instances.go
> +		DeviceID: serverID,
It's probably a minor use case, but I think we might want to filter by device_owner too even if Nova[^1] is arrogant enough to not consider other Neutron consumers. See https://bugs.launchpad.net/neutron/+bug/1982373 for context on how we hit that problem in the past. Even if it's "invalid" at the moment, I believe it should be fixed at some point.

[^1]: https://github.com/openstack/nova/blob/27.1.0/nova/api/openstack/compute/attach_interfaces.py#L74

2023-05-23 16:45 UTC, dulek commented on pkg/openstack/instancesv2.go
> +		klog.Errorf("unable to access compute v2 API : %v", err)
That's network v2 API.

2023-05-24 10:36 UTC, kayrus commented
@mdbooth I don't think it's a good idea. We need to keep the interfaces order, listing neutron ports doesn't provide the exact order. See #863

2023-05-24 11:29 UTC, mdbooth commented
You're thinking of server.Addresses, which preserves order. This change doesn't affect that. The API it replaces also doesn't guarantee order.

2023-05-24 11:42 UTC, kayrus commented
@mdbooth interesting. so it looks like the neutron default order is a timestamp, right? When an interface is attached to a node, neutron creates a port and the port gets the recent timestamp. If this order corresponds to the os-interfaces order, then I'm fine with a change ;)

2023-05-31 15:55 UTC, mdbooth commented
@zetaab @jichenjc Could we merge this?

2023-05-31 19:27 UTC, zetaab approved these changes
wow this looks interesting. Thank you!

/approve

2023-05-31 20:07 UTC, merged