Improved the grammar in sidecarcompatibility.md
kubernetes/cloud-provider-openstack pull request #2292
Opened 2023-07-07 12:33 UTC by Vikash-8090-Yadav

**What this PR does / why we need it**:
I improved some sentences which are misspelt and some grammar as well for a better user experience. 

**Special notes for reviewers**:

**Release note**:

```release-note
NONE
```

2023-07-07 15:52 UTC, dulek requested changes

2023-07-07 15:52 UTC, dulek commented on docs/cinder-csi-plugin/sidecarcompatibility.md
> +There is a change in [CSI-provisioner 2.0](https://github.com/kubernetes-csi/external-provisioner/blob/master/CHANGELOG/CHANGELOG-2.0.md): The fsType on provisioned PVs no longer defaults to "ext4".
I'd remove the dash between CSI-provisioner, seems like they go without in their README: https://github.com/kubernetes-csi/external-provisioner/tree/master.

Linked release note uses `fstype` as the name of the property, let's stick to that. `defaultFSType` is fine, but please use ticks to mark it as code.

2023-07-07 15:52 UTC, dulek commented on docs/cinder-csi-plugin/sidecarcompatibility.md
> +By default, in the manifest file with the `--default-fstype=ext4` default settings are added to [manifests](../../manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml), if you want to update
"with the" change seems incorrect.

2023-07-07 16:11 UTC, Vikash-8090-Yadav commented
Done with the changes,Thaks!

2023-07-10 15:36 UTC, mdbooth reviewed
/lgtm

2023-07-11 01:15 UTC, jichenjc commented
/approve

2023-07-11 01:27 UTC, merged