[occm] Add octavia listener xForwardedProto option
kubernetes/cloud-provider-openstack pull request #2362
Opened 2023-09-17 16:51 UTC by sungwon-ahn

**What this PR does / why we need it**:
Octavia provides the insert_header option as shown below. However, in OCCM, only X-Forwarded-For is available. As a result, we have implemented code to enable you to utilize this functionality in relation to XFP.

(You can find more information about this in the [documentation](https://docs.openstack.org/api-ref/load-balancer/v2/index.html?expanded=create-listener-detail#header-insertions))

**Which issue this PR fixes(if applicable)**:
fixes #

**Special notes for reviewers**:

**Release note**:

```release-note
[openstack-cloud-controller-manager]  The x-forwarded-protocol of the Octavia listener is supported.
```

2023-09-18 09:53 UTC, mdbooth commented
Can you describe your full end-to-end use case for this feature?

2023-09-18 13:55 UTC, dulek requested changes

2023-09-18 13:55 UTC, dulek commented on pkg/openstack/loadbalancer.go
> +		}
This completely duplicates the code above, please extract it to a function so that we can avoid repeating it.

2023-09-18 13:55 UTC, dulek commented on pkg/openstack/loadbalancer.go
>  	}
This if does exactly the same thing as the previous one. You should join them.

2023-09-18 13:55 UTC, dulek commented on pkg/openstack/loadbalancer.go
> +			return listeners.ProtocolHTTP
This if does exactly the same thing as the previous one. You should join them.

2023-09-18 13:55 UTC, dulek commented
There are more header insertions supported by Octavia. I think instead of implementing them one-by-one using annotations we may want to aim at creating a single annotation that will take a list of them and then OCCM will read that and populate InsertHeaders accordingly.

2023-09-19 14:46 UTC, sungwon-ahn commented
> Can you describe your full end-to-end use case for this feature?

Hi mdbooth! thx you for asking

I think it is necessary in the SSL offloading use case.

Octavia(HTTPS) < - > Nginx (HTTP)  <-> Pod (HTTP)
The k8s external type load balancer uses Octavia to use TERMINED_HTTP. In this case, the API server in the pod generates a response to the request in http.

2023-09-25 09:56 UTC, mdbooth commented
> > Can you describe your full end-to-end use case for this feature?
> 
> Hi mdbooth! thx you for asking
> 
> I think it is necessary in the SSL offloading use case.
> 
> Octavia(HTTPS) < - > Nginx (HTTP) <-> Pod (HTTP)
> 
> You can enable the HTTPS protocol when using a load balancer of the load balancer type in Octavia.
> 
> In this use case, HTTPS requests passing through Octavia must be translated to HTTP and forwarded to the Pod (backend API server).
> 
> You can identify the protocol being used in this request by checking the 'x-forwarded-protocol' header.

Would you be able to use the Octavia ingress controller instead for this use case? I worry in general about continuing to add annotations to service objects.

2023-09-26 10:03 UTC, jichenjc commented
/ok-to-test

2024-03-30 04:58 UTC, closed without merging