test : nodeAddressForLB()
kubernetes/cloud-provider-openstack pull request #2391
Opened 2023-10-05 07:06 UTC by KingDaemonX

**What this PR does / why we need it**:

**Which issue this PR fixes(if applicable)**:
fixes #

**Special notes for reviewers**:

**Release note**:

```release-note
NONE
```
implemented unitest for all possible edge case that this function can encounter checking in strategic range

2023-10-06 15:29 UTC, dulek requested changes
Wow, nice work, extensive number of cases! Please just fix the problem with manual comparisons instead of asserts and I think this is good to go.

2023-10-06 15:29 UTC, dulek commented on pkg/openstack/loadbalancer_test.go
> +			}
Please make sure to use `assert.Equal()` and `assert.*Error*()` methods instead of manual comparisons.

2023-10-06 15:29 UTC, dulek commented
/ok-to-test

2023-10-06 20:26 UTC, KingDaemonX commented
/test pull-cloud-provider-openstack-check

2023-10-09 18:18 UTC, dulek requested changes

2023-10-11 10:01 UTC, KingDaemonX commented on pkg/openstack/loadbalancer_test.go
> +			}
noted !
i already made the mod

2023-10-12 05:59 UTC, KingDaemonX commented
/retest

2023-10-12 06:01 UTC, KingDaemonX commented
/retest

2023-10-12 16:01 UTC, dulek requested changes
Ah, I've just noticed this, in some cases you should throw in some other address types to make sure they're ignored [1], e.g. `NodeExternalDNS`.

[1] https://github.com/kubernetes/cloud-provider-openstack/blob/3cbb728ba80b15a7cc66b9a936bfa78cb62b5c9c/pkg/openstack/loadbalancer.go#L611

2023-10-16 16:37 UTC, KingDaemonX commented
@pierreprinetti if you have the time, this is kinda good to go and just needs a /lgtm tag

2023-10-17 08:13 UTC, pierreprinetti approved these changes
LGTM! Thank you for your contribution.

2023-10-17 08:16 UTC, pierreprinetti commented
/approve
/lgtm

2023-10-17 08:17 UTC, pierreprinetti commented
@jichenjc @kayrus PTAL

2023-10-18 00:35 UTC, jichenjc commented
/approve
/hold 

seems some conflict need to be solved? let's solve this then unhold

2023-10-18 02:17 UTC, KingDaemonX commented
@jichenjc i just rebased and ready to check and go

2023-10-18 02:41 UTC, jichenjc commented
/unhold

2023-10-18 02:52 UTC, KingDaemonX commented
i think it needs a /lgtm to also be merged @jichenjc

2023-10-18 02:57 UTC, jichenjc commented
/lgtm

2023-10-18 03:00 UTC, merged

2023-10-18 03:22 UTC, KingDaemonX commented
@pierreprinetti thank you very much :)