[occm] add a node selector support for loadbalancer services
kubernetes/cloud-provider-openstack pull request #2601
Opened 2024-05-24 16:02 UTC by kayrus

**What this PR does / why we need it**:

This PR adds an ability to specify loadbalancer service with a node selector.

Big thanks to @ririko-nakamura for the [initial code](https://github.com/ririko-nakamura/cloud-provider-openstack/tree/target-node-labels-selector).

A new OCCM `node-selector` option is added into the `[LoadBalancer]` config section.
And a new `loadbalancer.openstack.org/node-selector` service annotation support is added.

**Which issue this PR fixes(if applicable)**:
fixes #1770

**Special notes for reviewers**:

**Release note**:

```release-note
added a node selector support for loadbalancer services
```

2024-05-24 19:50 UTC, zetaab requested changes
otherwise looks good, but perhaps worth of adding test for util.go stuff

also @ririko-nakamura is missing cla

2024-05-24 20:42 UTC, kayrus commented on pkg/util/util.go
> +func StringToMap(str string) map[string]string {
done

2024-05-25 06:36 UTC, zetaab approved these changes
/approve

2024-05-27 02:19 UTC, jichenjc approved these changes

2024-05-27 02:19 UTC, jichenjc commented on pkg/openstack/loadbalancer.go
> +		if nodeLabelValue, ok := node.Labels[k]; !ok || (v != "" && nodeLabelValue != v) {
not sure add a info.v(6) for the not match will be helpful for debug?

2024-05-27 02:19 UTC, jichenjc commented
/lgtm

2024-05-27 02:23 UTC, merged

2024-05-27 07:34 UTC, kayrus commented
@jichenjc @zetaab @dulek this PR is clearly a feature, and this improvement affects only selected environments. Keeping in mind that the default behavior wasn't changed, is there a chance we can cherry-pick the fix to earlier OCCM versions?

2024-05-27 07:40 UTC, jichenjc commented
generally only with bugs to backport..
but I think this unblock some use case so should be good backport if everyone agree

2024-05-27 17:32 UTC, kayrus commented
/cherry-pick release-1.30

2024-05-27 17:32 UTC, kayrus commented
/cherry-pick release-1.29

2024-05-27 17:32 UTC, kayrus commented
/cherry-pick release-1.28