[occm] LoadBalancer ProxyProtocol v2 feature
kubernetes/cloud-provider-openstack pull request #2635
Opened 2024-08-27 09:10 UTC by Lucasgranet

**What this PR does / why we need it**:
The PR brings the ability of choosing the ProxProtocol in version 2 (instead of v1).

Two new values are supported for `loadbalancer.openstack.org/proxy-protocol`
```yaml
loadbalancer.openstack.org/proxy-protocol: "true" # Enable ProxyProtocolv1
loadbalancer.openstack.org/proxy-protocol: "false" # Default value, no proxy protocol enable 
loadbalancer.openstack.org/proxy-protocol: "v1" # NEW - Enable ProxyProtocolv1
loadbalancer.openstack.org/proxy-protocol: "v2" # NEW - Enable ProxyProtocolv2
```

**Which issue this PR fixes(if applicable)**:
fixes #2585

**Special notes for reviewers**:
N/A

**Release note**:

```release-note
[openstack-cloud-controller-manager] Support LoadBalancer ProxyProtocol v2 feature
```

2024-09-02 05:11 UTC, zetaab commented
/ok-to-test

2024-09-02 05:18 UTC, zetaab requested changes

2024-09-02 05:18 UTC, zetaab commented on pkg/openstack/loadbalancer.go
> +func getProxyProtocolFromServiceAnnotation(service *corev1.Service) (bool, *v2pools.Protocol) {
this could return just `*v2pools.Protocol`? boolean is not really needed.

2024-09-02 05:18 UTC, zetaab commented on pkg/openstack/loadbalancer.go
>  	if svcConf.enableProxyProtocol {
instead of checking this boolean, you could use

```
if svcConf.proxyProtocolVersion != nil {
  poolProto = *svcConf.proxyProtocolVersion
}
```

2024-09-02 05:18 UTC, zetaab commented on pkg/openstack/loadbalancer.go
>  	if svcConf.enableProxyProtocol {
```
if svcConf.proxyProtocolVersion != nil {
  poolProto = *svcConf.proxyProtocolVersion
}
```

2024-09-02 05:18 UTC, zetaab commented on pkg/openstack/loadbalancer.go
> +func getProxyProtocolFromServiceAnnotation(service *corev1.Service) (bool, *v2pools.Protocol) {
in all other places where `svcConf.enableProxyProtocol` is used, you could just use `svcConf.proxyProtocolVersion != nil`

2024-09-02 08:43 UTC, Lucasgranet commented
@zetaab I'm not sure but E2E's failures seem not related to my PR.

Can you have a look please?

2024-09-02 09:10 UTC, zetaab commented
/test openstack-cloud-controller-manager-e2e-test
/test openstack-cloud-controller-manager-ovn-e2e-test

2024-09-02 11:30 UTC, zetaab commented
@Lucasgranet can you rebase this pr against master? Master contain fixes for the e2e tests

2024-09-02 12:14 UTC, Lucasgranet commented
/retest

2024-09-02 12:38 UTC, zetaab approved these changes
/approve

Thank you @Lucasgranet

2024-09-03 07:24 UTC, jichenjc commented
>>>loadbalancer.openstack.org/proxy-protocol: "true" # Enable ProxyProtocolv1

from this comment I think default is still v1, correct ?

2024-09-03 07:26 UTC, jichenjc commented on docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
> +
ok, saw this :)

2024-09-03 07:27 UTC, jichenjc commented
/lgtm

2024-09-03 09:08 UTC, zetaab commented
/lgtm

2024-09-03 09:09 UTC, merged