[cinder-csi-plugin] fix global config requirement for node-service
kubernetes/cloud-provider-openstack pull request #2678
Opened 2024-09-27 13:03 UTC by kayrus

**What this PR does / why we need it**:

**Which issue this PR fixes(if applicable)**:
fixes #2677

**Special notes for reviewers**:

**Release note**:

```release-note
[cinder-csi-plugin] fix global config requirement for node-service
```

2024-09-27 13:21 UTC, kayrus commented
/cherry-pick release-1.31

2024-09-30 07:47 UTC, zetaab requested changes
@kayrus could you add example of minimal cloud configuration for noClient usecase?

2024-09-30 07:48 UTC, kayrus commented
> could you add example of minimal cloud configuration

your example is fair enough

2024-09-30 08:38 UTC, zetaab commented
/lgtm

2024-09-30 12:09 UTC, sergelogvinov approved these changes

2024-10-01 13:38 UTC, dulek commented
/approve

2024-10-01 13:39 UTC, merged